version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/lambda"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "ajv"
        update-types: ["version-update:semver-major"]
